name: morning-cron

on:
  schedule:
    - cron: '30 19 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://sydney-news.vercel.app/api/get-news'